[package]
name = "rten-untyped"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
once_cell = "1.18.0"
rten-core = { path = "../rten-core" }
